/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blooddonationmanagementsystemfinal;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rakiba
 */
public class EditDashboard extends javax.swing.JFrame {

    String UserId;
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form EditDashboard
     */
    public EditDashboard() {
        initComponents();
        con = DBConnection.ConnectionDB();
    }
    public EditDashboard(String UserId) {
        this.UserId = UserId;
        initComponents();
        con = DBConnection.ConnectionDB();
        fatchData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editPanel = new javax.swing.JPanel();
        updateLastName = new javax.swing.JTextField();
        updateFirstName = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        UpdatedphoneNumber = new javax.swing.JTextField();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        updateDayOfBirth = new javax.swing.JComboBox<>();
        updateMonthOfBirth = new javax.swing.JComboBox<>();
        updateYearOfBirth = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        updateBloodGroup = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        updateProfileBtn = new javax.swing.JButton();
        updateArea = new javax.swing.JTextField();
        updateDistrict = new javax.swing.JTextField();
        updateCountry = new javax.swing.JTextField();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        UpdateDayOfDonate = new javax.swing.JComboBox<>();
        updateMonthOfDonate = new javax.swing.JComboBox<>();
        updateYearOfDonate = new javax.swing.JComboBox<>();
        backEditBtn = new javax.swing.JButton();
        UpdateLdodNever = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editPanel.setBackground(new java.awt.Color(255, 255, 255));

        updateLastName.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        updateFirstName.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel3.setText("Update First Name  : ");

        jLabel5.setText("Update Phone Number  : ");

        UpdatedphoneNumber.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        UpdatedphoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatedphoneNumberActionPerformed(evt);
            }
        });

        jLabel8.setText("Update Date of Birth  : ");

        updateDayOfBirth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        updateMonthOfBirth.setMaximumRowCount(6);
        updateMonthOfBirth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        updateYearOfBirth.setMaximumRowCount(6);
        updateYearOfBirth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));

        jLabel10.setText("Update Blood Group  : ");

        updateBloodGroup.setMaximumRowCount(6);
        updateBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select your group", "A +ve", "A -ve", "B +ve", "B -ve", "O +ve", "O -ve", "AB +ve", "AB -ve" }));

        jLabel11.setText("Update Address : ");

        updateProfileBtn.setBackground(new java.awt.Color(51, 204, 0));
        updateProfileBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        updateProfileBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateProfileBtn.setText("Update Now");
        updateProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileBtnActionPerformed(evt);
            }
        });

        updateArea.setText("Area Name");
        updateArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                updateAreaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateAreaFocusLost(evt);
            }
        });

        updateDistrict.setText("District");
        updateDistrict.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                updateDistrictFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateDistrictFocusLost(evt);
            }
        });

        updateCountry.setText("Country");
        updateCountry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                updateCountryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateCountryFocusLost(evt);
            }
        });

        jLabel12.setText("Update Last Donate : ");

        UpdateDayOfDonate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        updateMonthOfDonate.setMaximumRowCount(6);
        updateMonthOfDonate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        updateYearOfDonate.setMaximumRowCount(6);
        updateYearOfDonate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));

        backEditBtn.setBackground(new java.awt.Color(51, 204, 0));
        backEditBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        backEditBtn.setForeground(new java.awt.Color(255, 255, 255));
        backEditBtn.setText("Back");
        backEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backEditBtnActionPerformed(evt);
            }
        });

        UpdateLdodNever.setText("Never");
        UpdateLdodNever.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                UpdateLdodNeverItemStateChanged(evt);
            }
        });
        UpdateLdodNever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateLdodNeverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Update Your Profile");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdatedphoneNumber)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(updateFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(updateLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateArea, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UpdateLdodNever)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateDayOfDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateMonthOfDonate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(updateYearOfDonate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(updateDayOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateMonthOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(updateYearOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(backEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdatedphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateDayOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateMonthOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateYearOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateArea, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateDayOfDonate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateMonthOfDonate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateYearOfDonate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateLdodNever))
                .addGap(18, 18, 18)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateProfileBtn)
                    .addComponent(backEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel6.setText("Update Last Name : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(editPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(395, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(editPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void fatchData(){
        String sql0 = "select * FROM Users_info where user_id LIKE ?";
        try{
        pst = con.prepareStatement(sql0);
            pst.setString(1, UserId);
            rs = pst.executeQuery();

            
            while (rs.next()) {
                String fName = rs.getString("first_name");
                String lName =  rs.getString("last_name");
                String bloodGroup = rs.getString("blood_group");
                String contact = rs.getString("contact");
                String ldod = rs.getString("ldod");
                String area = rs.getString("area");
                String district = rs.getString("district");
                String country = rs.getString("country");
                
                updateFirstName.setText(fName);
                updateLastName.setText(lName);
                UpdatedphoneNumber.setText(contact);
                updateArea.setText(area);
                updateDistrict.setText(district);
                updateCountry.setText(country);
                
//                dateOfBirthLabel.setText(date);
                
                updateBloodGroup.setSelectedItem(bloodGroup);

                

                updateFirstName.paintImmediately(updateFirstName.getVisibleRect());
                
                
                
            }
        }catch(Exception e){
            System.out.println(e);
        }finally{
            try {
                pst.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }
    private void UpdatedphoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatedphoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdatedphoneNumberActionPerformed

    private void updateProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileBtnActionPerformed
        // TODO add your handling code here:
          String sql = "UPDATE Users_info SET first_name=?,last_name=?,blood_group=?,contact=?,dob=?,ldod=?,area=?,district=?,country=? WHERE user_id=?";

        try{

            String date =  updateYearOfBirth.getSelectedItem().toString() +"-"+ updateMonthOfBirth.getSelectedItem().toString() +"-"+updateDayOfBirth.getSelectedItem().toString();
            String lastDateOfDonation = updateYearOfDonate.getSelectedItem().toString()+"-"+ updateMonthOfDonate.getSelectedItem().toString() +"-"+ UpdateDayOfDonate.getSelectedItem().toString() ;
//            String gen = maleBtn.isSelected() == true ? "male" : femaleBtn.isSelected() == true ? "female" : otherBtn.isSelected() == true ? "Other" : "null";

            String FirstName = updateFirstName.getText();
            String BloodGroup = updateBloodGroup.getSelectedItem().toString();
            String _area = updateArea.getText();
            String _district = updateDistrict.getText();
            String _coun = updateCountry.getText();

            if(_area.equals("Area Name") || _district.equals("District")|| _coun.equals("Country") || FirstName.isBlank() || BloodGroup.equals("select your group")){
                JOptionPane.showMessageDialog(null, "Some Fields Are Required");
                return;
            }

            //            solving birth date exception
            try{
                java.sql.Date.valueOf(date);

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Date of Birth is Required!");
                return;
            }

            //            solve last date of donation exception
            try{
                java.sql.Date.valueOf(lastDateOfDonation);
            }catch(Exception e){
                lastDateOfDonation = "1950-01-01";
            }

            pst = con.prepareStatement(sql);

            pst.setString(1, FirstName);
            pst.setString(2, updateLastName.getText());
            pst.setString(3, BloodGroup);
            pst.setString(4, UpdatedphoneNumber.getText());
            pst.setString(5, date);
            pst.setString(6, lastDateOfDonation);
            pst.setString(7, _area);
            pst.setString(8, _district);
            pst.setString(9, _coun);
            pst.setString(10, UserId);
            
//            pst.setInt(13, 0);

            pst.executeUpdate();
        }
        catch(Exception e){
            System.out.println(e);
        }
        finally{
            try {
                pst.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_updateProfileBtnActionPerformed

    private void updateAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateAreaFocusGained
        // TODO add your handling code here:
        if("Area Name".equals(updateArea.getText())){
            updateArea.setText("");
        }
    }//GEN-LAST:event_updateAreaFocusGained

    private void updateAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateAreaFocusLost
        // TODO add your handling code here:
        if("".equals(updateArea.getText())){
            updateArea.setText("Area Name");
        }
    }//GEN-LAST:event_updateAreaFocusLost

    private void updateDistrictFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateDistrictFocusGained
        // TODO add your handling code here:
        if("District".equals(updateDistrict.getText())){
            updateDistrict.setText("");
        }
    }//GEN-LAST:event_updateDistrictFocusGained

    private void updateDistrictFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateDistrictFocusLost
        // TODO add your handling code here:
        if("".equals(updateDistrict.getText())){
            updateDistrict.setText("District");
        }
    }//GEN-LAST:event_updateDistrictFocusLost

    private void updateCountryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateCountryFocusGained
        // TODO add your handling code here:
        if("Country".equals(updateCountry.getText())){
            updateCountry.setText("");
        }
    }//GEN-LAST:event_updateCountryFocusGained

    private void updateCountryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateCountryFocusLost
        // TODO add your handling code here:
        if("".equals(updateCountry.getText())){
            updateCountry.setText("Country");
        }
    }//GEN-LAST:event_updateCountryFocusLost

    private void backEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backEditBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backEditBtnActionPerformed

    private void UpdateLdodNeverItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_UpdateLdodNeverItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_UpdateLdodNeverItemStateChanged

    private void UpdateLdodNeverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateLdodNeverActionPerformed
        // TODO add your handling code here:
        if(UpdateLdodNever.isSelected()){
            System.out.println("selected");
            UpdateDayOfDonate.setEnabled(false);
            updateMonthOfDonate.setEnabled(false);
            updateYearOfDonate.setEnabled(false);
        }else{
            System.out.println("unselected");
            UpdateDayOfDonate.setEnabled(true);
            updateMonthOfDonate.setEnabled(true);
            updateYearOfDonate.setEnabled(true);
        }
    }//GEN-LAST:event_UpdateLdodNeverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> UpdateDayOfDonate;
    private javax.swing.JCheckBox UpdateLdodNever;
    private javax.swing.JTextField UpdatedphoneNumber;
    private javax.swing.JButton backEditBtn;
    private javax.swing.JPanel editPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField updateArea;
    private javax.swing.JComboBox<String> updateBloodGroup;
    private javax.swing.JTextField updateCountry;
    private javax.swing.JComboBox<String> updateDayOfBirth;
    private javax.swing.JTextField updateDistrict;
    private javax.swing.JTextField updateFirstName;
    private javax.swing.JTextField updateLastName;
    private javax.swing.JComboBox<String> updateMonthOfBirth;
    private javax.swing.JComboBox<String> updateMonthOfDonate;
    private javax.swing.JButton updateProfileBtn;
    private javax.swing.JComboBox<String> updateYearOfBirth;
    private javax.swing.JComboBox<String> updateYearOfDonate;
    // End of variables declaration//GEN-END:variables
}
